### ISSUE TITLE
Script Unable to Execute

### ISSUE THREAD

**Issue by tiredofit** [rggassner/gassnerZabbixScripts#1]
Great work on the script. It looks to be exactly what I am after with Discovering Docker Hosts that get their hostnames all bent out of shape. 
Sadly, I'm having troubles pulling this repo and executing, receiving alot of strange python errors related to indenting. Do you have an update?

**Comment by rggassner** [comment]
Hi,

- Can you please copy the error message?
- Which script are you running?
- Are you using Linux?


Best regards

Gassner

**Comment by tiredofit** [comment]
Hi, Alpine Linux inside Docker w/Python3. I've got it to work now after some linting of the file, for some reason it became corrupted when pulling from Git.
My Python is lacking and I'm trying to understand how this all fits together as I'm encountering issues during Auto Discovery that are setting the hostname (and the dns name) to something different, to which I'm trying to update from the zabbix inventory.hostname. Was hoping this script could be called during an action after discovery, but seems to be only affecting the hostname, not the DNS name in the zabbix entry and affecting all the records only on the zabbix server, not the proxy. So a whole bunch of issues that I'll need to overcome I think - sounds like I need to learn python.

**Comment by rggassner** [comment]
I have downloaded the script and it is working as expected.
