### ISSUE TITLE
Zabbix 4.4.7 import Temple ARP_Monitor failed

### ISSUE THREAD

**Issue by chunchaowei** [rggassner/gassnerZabbixScripts#3]
HI, 

     I try to use your ARP_Monitoring temple,  I looks zabbix enviroment “Mix version is 4.4.0”， but  config - host groups- templates  import failed。

failed Detail：Invalid tag "/zabbix_export/version": unsupported version number.

 Is it not support？

thankyou

**Comment by rggassner** [comment]
Hi, I am using it in version 5.0.8.

Not sure it will work on earlier versions.
